[package]
name = "dag"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
num_cpus = "1.16.0"
petgraph = { version = "0.7.1", features = ["serde-1"] }
raw_sync = "0.1.5"
rmp-serde = "1.3.0"
serde = { version = "1.0.217", features = ["derive"] }
shared_memory = "0.12.4"
